### ISSUE TITLE
Panic while computing `hash_tree_root` of `BeaconState`

### ISSUE THREAD

**Issue by Cravtos** [ralexstokes/ssz-rs#9]
Trying to compute `hash_tree_root` of `BeaconState` deserialized from `"consensus-spec-tests/tests/mainnet/phase0/operations/block_header/pyspec_tests/success_block_header/post.ssz_snappy"` results in panic:
```
thread 'phase0::state_transition::block_processing::tests::test_process_block_header' panicked at 'range end index 32 out of range for slice of length 0', C:\Users\cravt\.cargo\git\checkouts\ssz_rs-4493665f49c79d5a\af8292a\ssz_rs\src\list.rs:182:17
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\std\src\panicking.rs:517
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\panicking.rs:100
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\/library\core\src\slice\index.rs:41
   3: core::slice::index::impl$3::index_mut<u8>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\slice\index.rs:251
   4: core::slice::index::impl$1::index_mut<u8,core::ops::range::Range<usize> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\slice\index.rs:26
   5: alloc::vec::impl$17::index_mut<u8,core::ops::range::Range<usize>,alloc::alloc::Global>
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\alloc\src\vec\mod.rs:2508
   6: ssz_rs::list::List<ethereum_consensus::phase0::validator::Validator,1099511627776>::compute_hash_tree_root<ethereum_consensus::phase0::validator::Validator,1099511627776>
             at C:\Users\cravt\.cargo\git\checkouts\ssz_rs-4493665f49c79d5a\af8292a\ssz_rs\src\list.rs:182
   7: ssz_rs::list::impl$12::hash_tree_root<ethereum_consensus::phase0::validator::Validator,1099511627776>
             at C:\Users\cravt\.cargo\git\checkouts\ssz_rs-4493665f49c79d5a\af8292a\ssz_rs\src\list.rs:248
   8: ethereum_consensus::phase0::beacon_state::impl$14::hash_tree_root<8192,16777216,2048,1099511627776,65536,8192,2048,4096>
             at .\src\phase0\beacon_state.rs:64
   9: ethereum_consensus::phase0::state_transition::block_processing::tests::impl$0::execute
             at .\src\phase0\state_transition\block_processing.rs:834
  10: ethereum_consensus::phase0::state_transition::block_processing::tests::impl$0::execute_from_glob
             at .\src\phase0\state_transition\block_processing.rs:865
  11: ethereum_consensus::phase0::state_transition::block_processing::tests::test_process_block_header
             at .\src\phase0\state_transition\block_processing.rs:872
  12: ethereum_consensus::phase0::state_transition::block_processing::tests::test_process_block_header::closure$0
             at .\src\phase0\state_transition\block_processing.rs:871
  13: core::ops::function::FnOnce::call_once<ethereum_consensus::phase0::state_transition::block_processing::tests::test_process_block_header::closure$0,tuple$<> >
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
  14: core::ops::function::FnOnce::call_once
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Code for reproduction:
```rust
    fn test_panic() {
        let path = "consensus-spec-tests/tests/mainnet/phase0/operations/block_header/pyspec_tests/success_block_header/post.ssz_snappy";
        let post_state = read_ssz_snappy_from_test_data(&path).expect("file exists");
        let mut post_state: BeaconState = deserialize(&post_state).expect("can deserialize");
        let result = post_state.hash_tree_root();
        println!("{:?}", result);
    }
```

**Comment by ralexstokes** [comment]
I am not exactly sure but I think this was fixed here: https://github.com/ralexstokes/ssz-rs/commit/355e0ede8c5734df4ccb07f4dad902d486a9832c
